### ISSUE TITLE
Wrong API key

### ISSUE THREAD

**Issue by Joakim-T** [sfortis/openai_tts#11]
I've tried inputting the OpenAI API key in the "Add text-to-speech engine" dialog when adding integration but the input window just reloads. Tried multiple keys that work in other integrations.

Using the new 56 character API keys.
Just installed openai_tts today so have the latest version.

I get the following in the logs..

```
Logger: custom_components.openai_tts.config_flow
Source: custom_components/openai_tts/config_flow.py:56
integration: openai_tts ([documentation](https://github.com/sfortis/openai_tts/), [issues](https://github.com/sfortis/openai_tts/issues))
First occurred: 18:13:10 (4 occurrences)
Last logged: 18:14:28

Wrong or no API key provided.
Traceback (most recent call last):
  File "/config/custom_components/openai_tts/config_flow.py", line 56, in async_step_user
    await validate_input(user_input)
  File "/config/custom_components/openai_tts/config_flow.py", line 21, in validate_input
    raise WrongAPIKey
custom_components.openai_tts.config_flow.WrongAPIKey
```

**Comment by sfortis** [comment]
@Joakim-T 

Did you grab the files from the release? If yes, download them again; the release was outdated.

I've tested the new 56-character API keys, and it's fine.

**Comment by Joakim-T** [comment]
> @Joakim-T
> 
> Did you grab the files from the release? If yes, download them again; the release was outdated.
> 
> I've tested the new 56-character API keys, and it's fine.

@sfortis Downloaded the latest and now it works great.
Thanks for the help and thank you for making openai_tts :-)
