### ISSUE TITLE
Please add Khmer language models

### ISSUE THREAD

**Issue by sansopheakh** [sfortis/openai_tts#14]
Please add Khmer language model for OpenAI TTS and STT support.
There are lots of models in HuggingFace.
https://huggingface.co/models?language=km&sort=trending

**Comment by sfortis** [comment]
The supported models by openAI are these: https://platform.openai.com/docs/guides/text-to-speech 

STT is on the todo list ;)

**Comment by sansopheakh** [comment]
> The supported models by openAI are these: https://platform.openai.com/docs/guides/text-to-speech
> 
> STT is on the todo list ;)

Yes, i seen.
But there are no Khmer language in the supported language list. I wish you add it soon.
Thanks.
