### ISSUE TITLE
Add a short pause at the start of the audio clip to avoid cutting it off

### ISSUE THREAD

**Issue by raldone01** [sfortis/openai_tts#19]
Ideally the pause should be configurable.

**Comment by sfortis** [comment]
@raldone01 can you provide a case that audio is cutting off? actually i'm working to add a slight normalization / compression using ffmpeg so i can add it, but i never experienced something similar on various devices.

**Comment by raldone01** [comment]
I figured it out sorry. It was an issue with my audio setup.
