### ISSUE TITLE
Missing agent

### ISSUE THREAD

**Issue by BoKKeR** [sfortis/openai_tts#2]
![image](https://github.com/sfortis/openai_tts/assets/2664857/e19ec8fa-3d35-4d0d-8add-4656256b65b9)

Could you advice how to setup the AGENT ? Also in your video you call TTS, is this needed? If so how to set it up?

**Comment by sfortis** [comment]
Don't confuse them! Conversation is used to get a reply from assistants (like the build in home assistant or you can use OpenAI conversation to get replies via chatGPT (https://my.home-assistant.io/redirect/config_flow_start?domain=openai_conversation). TTS will render the reply to voice.

Remember, when you get the replies from OpenAI conversation, you need to extract only the actual message from json response using {{ gpt_response.response.speech.plain.speech }} template.
