### ISSUE TITLE
Enable voice selection in options (feature request)

### ISSUE THREAD

**Issue by codysaylor** [sfortis/openai_tts#4]
I'd like to be able to define the voice in the "options" field (and the other fields too, but primarily just voices), seen in Developer tools > services > call tts.openai_tts_say as well as Node-RED. I tried making some changes but I don't know much Python so I'm not sure the level of effort for this change. I think it would make sense to have defaults or be able to define them in configuration.yaml too.

**Comment by sfortis** [comment]
Yes, I was thinking to add this also. This needs a config_flow implementation and the yaml UI definition. I'll work on this at some point.

**Comment by codysaylor** [comment]
Awesome, thank you @sfortis !

**Comment by DanDixon** [comment]
I'd also like the ability to set the options from the service call: tts.openai_tts_say
Thanks for making this, it's cool!

**Comment by sfortis** [comment]
feature is added with the latest PR from @dvejsada
