### ISSUE TITLE
Enable Wyoming Protocol to use Integration in Assist

### ISSUE THREAD

**Issue by saya6k** [sfortis/openai_tts#5]
By Adding Wyoming Protocol support, I can use this in Assist voice assistant.

Please Add Wyoming Protocol compatibility.

**Comment by sfortis** [comment]
Wyoming Protocol is used for local services (afaik!). You can use openai_tts with your assist right away. Its working fine from both desktop / mobile / watch assists.

![image](https://github.com/sfortis/openai_tts/assets/15342157/4679d700-e1ce-41ed-ba84-afdf5a28a0a7)

**Comment by saya6k** [comment]
Oh, yes it's working. My config was wrong. Thanks for reply. I'll close issue.
