### ISSUE TITLE
Language selection?

### ISSUE THREAD

**Issue by paull27** [sfortis/openai_tts#8]
The UI setup of the integration only asks for API key, speed, model and voice.
In the YAML version I was able to configure the language, how do I do that now?

**Comment by eponce92** [comment]
Agree, this feature is crucial. It's challenging to comprehend the output when attempting to use it in Spanish.

**Comment by sfortis** [comment]
There is no parameter in the OpenAI speech endpoint to explicitly set the output language. The language is determined by the language of the input text provided.

**Comment by thematrixdev** [comment]
@paull27 What is the YAML version? I need language selection as well.
